package com.dev.talking.spring.exception;

public enum ErrorCode {

	VALIDATION_ERROR,
	RESOURCE_NOT_FOUND,
	ENDPOINT_NOT_FOUND,
	METHOD_NOT_ALLOWED,
	MALFORMED_REQUEST,
	TYPE_MISMATCH,
	DATA_INTEGRITY_VIOLATION,
	INTERNAL_SERVER_ERROR
}
